backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
locale: "it"
collections:
  - name: "prodotti"
    label: "Prodotti"
    folder: "src/content/prodotti"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome", name: "title", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
      - {label: "Descrizione", name: "body", widget: "markdown"}